// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tecnoservicio/LandingDesktop.tsx": () => import("../components/mockups/tecnoservicio/LandingDesktop.tsx"),
  "./components/mockups/tecnoservicio/LandingMobile.tsx": () => import("../components/mockups/tecnoservicio/LandingMobile.tsx")
};
